---
repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: "argo-cd"
    chart: argo/argo-cd
    atomic: true
    namespace: "argocd"
    createNamespace: true
    installed: true
    labels:
      name: argocd
    version: 3.10.2
    values:
      - ./values.d/values.yaml
    missingFileHandler: Warn
