
name: 'Terraform Execution'

on:
  push:
    branches:
      - master
      - develop
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: 'Setup helmfile'
        uses: mamezou-tech/setup-helmfile@v0.8.0
      - name: vaildate
        run: |
          helmfile lint
          helmfile template
        env:
          ENVIRONMENT: ${{ env.ENV }}
          KUBE_NAMESPACE: ${{ env.KUBE_NAMESPACE }}
      - name: diff
        run: |
          helmfile diff
        env:
          ENVIRONMENT: ${{ env.ENV }}
          KUBE_NAMESPACE: ${{ env.KUBE_NAMESPACE }}

  sync:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: 'Setup helmfile'
        uses: mamezou-tech/setup-helmfile@v0.8.0
      - name: vaildate
        run: |
          helmfile lint
          helmfile template
        env:
          ENVIRONMENT: ${{ env.ENV }}
          KUBE_NAMESPACE: ${{ env.KUBE_NAMESPACE }}
      - name: diff
        run: |
          helmfile diff
        env:
          ENVIRONMENT: ${{ env.ENV }}
          KUBE_NAMESPACE: ${{ env.KUBE_NAMESPACE }}
