
name: 'Helmfile Execution'

on:
  push:
    branches:
      - master
      - develop
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        env:
          AWS_REGION: us-east-1
          KUBE_NAMESPACE: argocd
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: 'Setup helmfile'
        uses: mamezou-tech/setup-helmfile@v0.8.0
      - name: 'Validate templates'
        run: |
          helmfile lint
          helmfile template
      - name: Login to EKS
        run: |
          aws eks update-kubeconfig --name "ekoparty"
      - name: 'Helmfile diff'
        run: |
          helmfile diff --suppress-secrets

  sync:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        env:
          AWS_REGION: us-east-1
          KUBE_NAMESPACE: argocd
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: 'Setup helmfile'
        uses: mamezou-tech/setup-helmfile@v0.8.0
      - name: 'Validate templates'
        run: |
          helmfile lint
          helmfile template
      - name: Login to EKS
        run: |
          aws eks update-kubeconfig --name "ekoparty"
      - name: 'Helmfile diff'
        run: |
          helmfile diff --suppress-secrets
      - name: 'Helmfile sync'
        run: |
          helmfile sync
